CFLAGS += -I ../../os/include/compat/uapi
CFLAGS += -I ../../os/include/compat
CFLAGS += -I common

# Arithmetic with void*
CFLAGS += -Wno-pointer-arith

# Ignore #pragma unroll
CFLAGS += -Wno-unknown-pragmas

# Ignore weird address taking
CFLAGS += -Wno-address-of-packed-member

# Ignore weird comparisons
CFLAGS += -Wno-sign-compare

# Ignore lack of casts, which has no specific warning in GCC
CFLAGS += -Wno-error
