[package]
name = "rust-policer"
version = "1.0.0"

[lib]
crate-type = ["cdylib"]

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true
lto = true
codegen-units = 1
panic = 'abort'
